### ISSUE TITLE
Unable to install Jupyter Notebook within gridwxcomp environment

### ISSUE THREAD

**Issue by hwilkie-usgs** [WSWUP/gridwxcomp#10]
I can't open  a jupyter notebook within the gridwxcomp environment, and when I open a notebook in my base environment, it can't see the gridwxcomp environment.

Attempts to install jupyter notebook were met with failure, even after installing nb_conda_kernel as suggested by this [post](https://towardsdatascience.com/environment-management-with-conda-python-2-3-b9961a8a5097?)

The error seemed to be caused by a package inconsistency, as follows:

> The environment is inconsistent, please check the package plan carefully
> The following packages are causing the inconsistency:
> 
>   - conda-forge/win-64::fiona==1.8.13=py38hb7fdc2d_0
>   - conda-forge/noarch::rasterstats==0.14.0=py_0
> failed with initial frozen solve. Retrying with flexible solve.

I haven't worked with jupyter notebooks very much, so it's possible I am missing something very basic here. Has anyone else encountered this problem?

Many thanks in advance.

**Comment by JohnVolk** [comment]
Interesting, I tried a fresh install and I did not get the error. Perhaps the easiest thing to try first is to add jupyter to the environment.yml file and then reinstall from the file letting conda handle it. First start by removing your gridwxcomp environment:

`conda remove --name gridwxcomp --all`

Then add the following line to your environment.yml file:

`  - jupyter`

And reinstall from the file:

`conda env create -f environment.yml`

If this doesn't work you may also want to try installing a different version of rasterstats, my version that is working with fiona is 0.13. For example you could try removing rasterstats from your environment, install jupyter, and then reinstall rasterstats.  

`conda remove rasterstats`
`conda install jupyter -c conda-forge`
`conda install rasterstats -c conda-forge`

Let me know how it goes.
