### ISSUE TITLE
Minor type in column header

### ISSUE THREAD

**Issue by amygalanter** [WSWUP/gridwxcomp#11]
Awesome package! Thanks so much for creating such a useful and cool package!

I noticed a minor typo in the example_data StationST_Daily_output.csv, the column header was labeled 'Eto (mm)' which was throwing an error in the function calc_bias_ratios when grid_variable = 'eto_mm'

By changing it to 'ETo (mm)' with a capital 'T' instead of lowercase 't', the function worked.

**Comment by JohnVolk** [comment]
Thanks for finding this, I went ahead and updated the ETo headers in the example files!. Glad to hear you find the package useful!
