### ISSUE TITLE
Possible dataframe data type error due to pandas update 

### ISSUE THREAD

**Issue by amygalanter** [WSWUP/gridwxcomp#12]
An error was thrown in plot.py when I was running gridwxcomp.interpolate:
'pandas dataframe float object has no attribute astype' 

which corresponded to lines 734 and 735
        min_yr = df.start_year.min().astype(int)
        max_yr = df.end_year.max().astype(int)

I have pandas version 0.25.1, maybe this is the result of a pandas update, but when I made this change, I was able to run the function. 
        min_yr = int(df.start_year.min())
        max_yr = int(df.end_year.max())

I had the same error while running gridwxcomp.plot.daily_comparison for lines 143 and 144 of plot.py

Not sure if it is only with higher versions of pandas, I used the environment.yml file which specifies pandas>=0.24.

**Comment by JohnVolk** [comment]
Interesting, I just tested using pandas 0.25.3 and had no errors, strange... I also did some manual tests and all seemed to work fine, for example calling astype(int/float/str) on a pandas single value statistic from a dataframe or series works as expected. After thinking about it the error does make sense (depending on how Pandas handles it) but not sure why I don't get the error. I will probably go ahead and update just in case after looking into it a bit more, thanks again!
