### ISSUE TITLE
spatial.py ouput dir cannot match input dir of summary .csv (crashes)

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#13]
spatial.py will overwrite the input summary.csv (e.g. eto_mm_summary_comp_all_yrs.csv) and crash mid-run if the -i and -o folder locations match. 

Add check or modify "copied" filename, so overwrite doesn't erase original data file mid run.

**Comment by JohnVolk** [comment]
Hi Chris, there might be a misunderstanding on how the code saves files. You are trying to save the output rasters to the same folder that contains the input_summary.csv correct? For example you may be calling

`$ python spatial.py -i monthly_ratios/eto_mm_summary_comp_all_yrs.csv -o monthly_ratios`

If this is the case then the option to specify the output folder is probably not what you think it is. The way the folder structure is setup is that the rasters are always written beneath a subdirectory named "spatial"  and another subdirectory beneath that named for the interpolation algorithm and raster resolution, also the "spatial" directory is always created with the same folder as the input_summary.csv. For example, if the -o option is not specified the rasters will be saved to 

`/folder_with_input_summary/spatial/folder_named_by_interpolation_and_resolution/`

which by default would be

``monthly_ratios/spatial/etr_mm_invdist_0.00417_deg/`

If you specify the output dir  for example -o my_output_dir then the rasters (and other associated output) will be written to

`/folder_with_input_summary/spatial/folder_named_by_interpolation_and_resolution/my_output_dir/`

I also get an error with writing the output interpolated raster if I call 

`$ python spatial.py -i monthly_ratios/eto_mm_summary_comp_all_yrs.csv -o monthly_ratios`

however I do not think this is what you want, if it did work it would save output to:

`monthly_ratios/spatial/etr_mm_invdist_0.00417_deg/monthly_ratios/`

I am assuming you want the output ratios in the first "monthly_ratios" folder? 

If I run however, 

`$ python spatial.py -i monthly_ratios/eto_mm_summary_comp_all_yrs.csv -o anything_else`

it works as expected with output saved to

`monthly_ratios/spatial/etr_mm_invdist_0.00417_deg/anything_else/`

The way the code is designed with internal references to different locations the output directory cannot be changed except for the name of the subdirectory under a specific interpolation option as shown above. This is explained in the docs example for `spatial.interpolate`  API, but i'll paste it here:

```python
from gridwxcomp import spatial
summary_file = 'monthly_ratios/etr_mm_summary_comp_all_yrs.csv'
buffer = 10
layer = 'annual_mean'
params = {'power':1, 'smooth':20}
out_dir = 's20_p1' # optional subdir name for saving rasters
interpolate(summary_file, layer=layer, out=out_dir,
    scale_factor=0.1, params=params, buffer=buffer)
```
Will produce the following output structure:
```
monthly_ratios/
├── etr_mm_summary_all_yrs.csv
├── etr_mm_summary_comp_all_yrs.csv
└── spatial/
    ├── etr_mm_invdist_400m/
    │   └── s20_p1/
    │       ├── annual_mean.tiff
    │       ├── annual_mean.vrt
    │       ├── etr_mm_summary_comp_all_yrs.csv
    │       ├── etr_mm_summary_pts.cpg
    │       ├── etr_mm_summary_pts.dbf
    │       ├── etr_mm_summary_pts.prj
    │       ├── etr_mm_summary_pts.shp
    │       ├── etr_mm_summary_pts.shx
    │       ├── zonal_stats.csv
    │       └── residual_plots
    │           └── annual_res.html
    ├── grid.cpg
    ├── grid.dbf
    ├── grid.prj
    ├── grid.shp
    └── grid.shx
```
The key here is that the user does not have control over "spatial" and the "etr_mm_invdist_400m" folder names or locations, only the subdirectory after "etr_mm_invdist_400m" which has been subsequently changed to use raster resolution in decimal degrees in more recent versions.

As for overwriting the input summary CSV, I do not get that issue, the code internally rewrites it with the same values but does not overwrite. But this shouldn't be an issue as long as you do not try to name the subdir raster output folder exactly as the folder of the input summary.csv.  If you are really needing to save rasters to something like 

`monthly_ratios/spatial/etr_mm_invdist_0.00417_deg/monthly_ratios/`

where your input summary CSV is in the first "monthly_ratios" directory and your output is in the "monthly_ratios" child directory, then it may require some reworking of the code, but I have a hunch this is not what were thinking anyways. Hopefully this helps explain the file structure of gridwxcomp output.

**Comment by cpearson1** [comment]
Thanks for breakdown. I was specifying the subdir raster output folder exactly the same as the folder with input summary csv. This over writes the input csv in the middle of the run. 

Changing the -o folder fixed my problem. Can we add a check to throw a warning error if -o folder matches the location of the input summary .csv?

**Comment by JohnVolk** [comment]
Yes, done!
