### ISSUE TITLE
ploy.py: regression through zero fails with negative values

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#15]
![image](https://user-images.githubusercontent.com/14983120/72561172-7be5e780-385d-11ea-876e-807f7e1a0545.png)

**Comment by JohnVolk** [comment]
Cannot reproduce this, it seems to work for negative values in all cases I have run. Is this still occurring on your end?
![Screenshot from 2021-04-26 21-54-35](https://user-images.githubusercontent.com/7738538/116173228-322fb200-a6da-11eb-95a8-f00ab8a2c072.png)
