### ISSUE TITLE
daily summary time series plots (separate 1to1 and daily time series figures)

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#16]
The daily time series figures are summarized by month. 1 to 1 comparison plots make sense at the monthly time step, but the time series figures look awkward due to the interpolation between each year (e.g. January to January).

![image](https://user-images.githubusercontent.com/14983120/73029770-0e056700-3ded-11ea-8250-9913016d0286.png)

Suggested Change:
Remove time series subplots from monthly figures. Keep 1 to 1 subplots only. 
Generate complete daily timeseries plot for entire station/gridmet comparison length  (i.e. all months/all data) .

**Comment by JohnVolk** [comment]
Thanks Chris, I haven't modified the basic function of the daily and monthly time series plots since you originally wrote them with the exception of file structure, i/o. Another option that I will try first is to change the x-axis to the monthly time series which should remove the gaps in the figure.

**Comment by JohnVolk** [comment]
Was a little bit tougher to figure out than I thought just to collapse the gaps but I got it working, now the daily comparison plots will produce something like this (two years of example data from 2017-2018):

![Screenshot from 2020-01-23 20-25-30](https://user-images.githubusercontent.com/7738538/73037960-c697ce80-3e1e-11ea-845e-73ff08d95ae8.png)

Let me know what you think, for now will be pushing changes as this appears better and maintains the functionality of the daily time series comparisons.
