### ISSUE TITLE
add wind direction as optional output

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#19]
Can we add gridMET wind direction as an optional output in the download_girdmet_opendap.py tool? 
Default output files should not include wind direction. 

Here is the variable name information:
![image](https://user-images.githubusercontent.com/14983120/101510884-4fcccc80-392f-11eb-95b5-8ec9e92f80a4.png)

**Comment by JohnVolk** [comment]
The last commit [5e76854](https://github.com/WSWUP/gridwxcomp/commit/5e768546b5d2c65dfde23c4cd727987fc0d78650) added this as an optional download. 

To use from the command line add the following:

```
 --optional-vars th
```

or from the ``download_gridmet_opendap`` function pass a list or a comma separated string:

``` python
download_gridmet_opendap(
    'merged_input.csv', 'folder for gridMET data', optional_vars=['th']
)
```

I updated a few things to make adding additional optional variables easy in the future by writing the argument as a list or comma separated string.
