### ISSUE TITLE
addition of pair_kpa column creates conflict with appending to older files

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#21]
Adding pair_kpa to newer downloads creates an issue with the .dropna() on line 346. Results in file with only updated data (no original data). 

Consider adding option to recognize old vs new files or other higher level fix.

**Comment by JohnVolk** [comment]
Not sure if I follow, how is pair_kpa not in the older/original data? It should be calculated each time the download function is run using elevation.

**Comment by cpearson1** [comment]
Prior to the commit #19 on Jan 7, pair_kpa wasn't included in the output.
https://github.com/WSWUP/gridwxcomp/commit/5e768546b5d2c65dfde23c4cd727987fc0d78650#diff-18504c5df0a32640e121acee828b33494158f16efb2c98b9345f7a8d4863312bR86

This is just something to be aware of moving forward. I think we can close the issue.

**Comment by JohnVolk** [comment]
Ah didn't realize, OK `dropna(how='all')` should fix this by not dropping the older rows (dates) that have all columns except pair_kpa. I'll go ahead and make the change.
