### ISSUE TITLE
Add VPD as optional export variable in download_gridmet_opendap.py

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#22]
http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_met_vpd_1979_CurrentYear_CONUS.nc.html

vpd_kpa

**Comment by JohnVolk** [comment]
FYI, when testing the VPD download update in commit 91998b5827a8069563394b797b253e33c546765f I noticed one of four sites I tested on returned all null values, I ran it twice and tried manually on the server page and it also returned nulls.
