### ISSUE TITLE
Consider adding a try/except/retry option to the opendap gridmet download tool

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#23]
The error below occurs occasionally when downloading from the northwest knowledge site using the opendap download tool. Consider adding a retry loop to avoid random stops when downloading multiple locations. 

![image](https://user-images.githubusercontent.com/14983120/204431441-5b3ef037-d282-44e5-9686-74f4991c4ef7.png)

**Comment by JohnVolk** [comment]
Commit #[d3a3397](https://github.com/WSWUP/gridwxcomp/commit/d3a339711e26f9b86b262c7a0c378d06ef7dd39e) added a loop to retry the download up to three times in case it fails, if that fixes the issue go ahead and close thanks!
