### ISSUE TITLE
Can't create the gridwxcomp environment

### ISSUE THREAD

**Issue by ThomasOtt314** [WSWUP/gridwxcomp#7]
I'm trying to install the conda environment for gridwxcomp from the command line. 

I've run the code <conda env create -f environment.yml> from the command line in my windows 10 pc. The return is <SpecNotFound: Can't process without a name>.

Thanks for your help.

**Comment by JohnVolk** [comment]
Hi Thomas, I've never seen that error but after looking it up I came upon another [GitHub issue](https://github.com/conda/conda/issues/3847#issuecomment-362884950) raised somewhere where they were able to corrected it by typing in the full path to the environment.yml file in their command line, e.g. C:\.path\to\environment.yml. Make sure you have the correct environment file downloaded and give that a try.
